logo: # add logo name
title: Abdurrezzak Efe's blog
description: > # this means to ignore newlines until "baseurl:"
  A science enthusiast and algorithms lover!
permalink: ':title/'
baseurl: "/bef" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Abdurrezzak Efe's Blog # add banner title
banner-desc: An algorithm lover's work! # add banner description

# Author settings
author-pic: me.jpg # your photo
author-name: Abdurrezzak Efe
about-author: Bilkent University Bachelor's in CS 2018'
email: abdurrezak.efe@ug.bilkent.edu.tr # your email
phone: +905423759612 # your pnone number
website: # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link 
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
